# Generated by Django 2.1.7 on 2019-03-11 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField(auto_created=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_name', models.CharField(max_length=150)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, validators=[django.core.validators.EmailValidator()])),
                ('address', models.TextField()),
            ],
        ),
    ]
