# Generated by Django 2.1.7 on 2019-03-12 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20190312_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(default='+989123456789', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='example: +989123456789', regex='^\\+?1?\\d{9,20}$')]),
            preserve_default=False,
        ),
    ]
