# Generated by Django 2.1.7 on 2019-03-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_auto_20190312_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user_name',
            new_name='username',
        ),
    ]
