# Generated by Django 2.1.7 on 2019-03-12 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_auto_20190312_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,20}$')]),
        ),
    ]
