# Generated by Django 2.1.7 on 2019-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
